spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taco_cloud?serverTimezone=UTC
    username: kangyuyang
    password: kang13832151179
    driver-class-name: com.mysql.jdbc.Driver
    
server:  port: 8443
  ssl:
    key-store: src/main/resources/mykeys.jks
    key-store-password: letmein
    key-password: letmein